[[JuliaNVTXCallbacks]]
arch = "aarch64"
git-tree-sha1 = "65f6b423cbdfde46a2f37e24e21c555323ff6dfa"
libc = "glibc"
os = "linux"

    [[JuliaNVTXCallbacks.download]]
    sha256 = "2cef47f4d482592492d6dab803483ee948178f8f1583b50d4e71e2715b4e3d2c"
    url = "https://github.com/JuliaBinaryWrappers/JuliaNVTXCallbacks_jll.jl/releases/download/JuliaNVTXCallbacks-v0.2.1+0/JuliaNVTXCallbacks.v0.2.1.aarch64-linux-gnu.tar.gz"
[[JuliaNVTXCallbacks]]
arch = "powerpc64le"
git-tree-sha1 = "6c1334ef239d129dc4550f4959cd298d97e4d9ec"
libc = "glibc"
os = "linux"

    [[JuliaNVTXCallbacks.download]]
    sha256 = "39a6f5facc71525881675f5f0f016db5f1d05a7767f1f0540395e0337f3e3ddb"
    url = "https://github.com/JuliaBinaryWrappers/JuliaNVTXCallbacks_jll.jl/releases/download/JuliaNVTXCallbacks-v0.2.1+0/JuliaNVTXCallbacks.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[JuliaNVTXCallbacks]]
arch = "x86_64"
git-tree-sha1 = "ff17ab283d1f7456123711f21d8b1d7e852f8024"
libc = "glibc"
os = "linux"

    [[JuliaNVTXCallbacks.download]]
    sha256 = "1b483ff465096e0bca50d66c296a7d5b5fd9007112ff54d4da14193590818953"
    url = "https://github.com/JuliaBinaryWrappers/JuliaNVTXCallbacks_jll.jl/releases/download/JuliaNVTXCallbacks-v0.2.1+0/JuliaNVTXCallbacks.v0.2.1.x86_64-linux-gnu.tar.gz"
[[JuliaNVTXCallbacks]]
arch = "x86_64"
git-tree-sha1 = "3ea9f3a9f9de597799a4530209707507f3f0d19a"
os = "windows"

    [[JuliaNVTXCallbacks.download]]
    sha256 = "6225d12a2f05aba20539ee6d2665d57a2aad3bdd8aca950b4f358d0807559443"
    url = "https://github.com/JuliaBinaryWrappers/JuliaNVTXCallbacks_jll.jl/releases/download/JuliaNVTXCallbacks-v0.2.1+0/JuliaNVTXCallbacks.v0.2.1.x86_64-w64-mingw32.tar.gz"
