[[JuliaNVTXCallbacks]]
arch = "aarch64"
git-tree-sha1 = "9d836dd8987c1059e835aef3e4332b26a4984599"
libc = "glibc"
os = "linux"

    [[JuliaNVTXCallbacks.download]]
    sha256 = "d97ed2b4cf2e19bb17009836eaa799ae0738f37df427ca292c69c118d0dd8a1e"
    url = "https://github.com/JuliaBinaryWrappers/JuliaNVTXCallbacks_jll.jl/releases/download/JuliaNVTXCallbacks-v0.2.0+0/JuliaNVTXCallbacks.v0.2.0.aarch64-linux-gnu.tar.gz"
[[JuliaNVTXCallbacks]]
arch = "powerpc64le"
git-tree-sha1 = "219e17f5957ecdf23f86e53cc8e5ce30a2d7a98c"
libc = "glibc"
os = "linux"

    [[JuliaNVTXCallbacks.download]]
    sha256 = "a9b4b19908f9cfa5d176d553b8def6643435306cbca95af25c2de75c1bc6ed70"
    url = "https://github.com/JuliaBinaryWrappers/JuliaNVTXCallbacks_jll.jl/releases/download/JuliaNVTXCallbacks-v0.2.0+0/JuliaNVTXCallbacks.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[JuliaNVTXCallbacks]]
arch = "x86_64"
git-tree-sha1 = "65166664c1b49b80d756b600ca90594e1dee8f0f"
libc = "glibc"
os = "linux"

    [[JuliaNVTXCallbacks.download]]
    sha256 = "ea83b7fc4dcf10ab6eab633ce60ad2a7e35df79976733982b42743294c65cbb9"
    url = "https://github.com/JuliaBinaryWrappers/JuliaNVTXCallbacks_jll.jl/releases/download/JuliaNVTXCallbacks-v0.2.0+0/JuliaNVTXCallbacks.v0.2.0.x86_64-linux-gnu.tar.gz"
[[JuliaNVTXCallbacks]]
arch = "x86_64"
git-tree-sha1 = "77ae72173c0824ff531b36b6d7761ddc425d47b6"
os = "windows"

    [[JuliaNVTXCallbacks.download]]
    sha256 = "294619a48bd21511d66f15fbf713afd95143855ef8bd4688205ebba849944288"
    url = "https://github.com/JuliaBinaryWrappers/JuliaNVTXCallbacks_jll.jl/releases/download/JuliaNVTXCallbacks-v0.2.0+0/JuliaNVTXCallbacks.v0.2.0.x86_64-w64-mingw32.tar.gz"
